Repository enveng-group/dev_greenova, pull requests merged in 2025-03, with the labels that each got.

#19 Chore/css refactor
  .env.vault
  greenova/chatbot/templates/chatbot/chat_widget.html
  greenova/chatbot/templatetags/chatbot_tags.py
  greenova/core/templates/core/components/breadcrumbs.html
  greenova/static/css/base.css
  greenova/static/css/components/breadcrumbs.css
  greenova/static/css/components/button.css
  greenova/static/css/components/chat.css
  greenova/static/css/components/form.css
  greenova/static/css/components/navigation.css
  greenova/static/css/defines/colours.css
  greenova/static/css/defines/design.css
  greenova/static/css/styles.css
  greenova/static/css/themes/dark.css
  greenova/static/css/themes/light.css
  greenova/templates/base.html
  package.json
Labels: enhancement

#24 feat: major project enhancements and infrastructure improvements
  Makefile
  greenova/greenova/settings.py
  greenova/users/apps.py
  greenova/users/models.py
  greenova/users/signals.py
Labels: bug, enhancement, Django

#25 update some .devcontainer/ file
  .devcontainer/.dockerignore
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  .devcontainer/package.json
  .devcontainer/requirements.txt
Labels: enhancement, Docker

#26 Feature/chatbot + Fixed Breadcrumbs (#13)
  greenova/chatbot/services.py
  greenova/chatbot/templates/chatbot/chat_widget.html
  greenova/chatbot/views.py
  greenova/static/css/components/charts.css
  greenova/static/css/components/chat.css
  greenova/static/css/defines/colours.css
  greenova/static/css/defines/design.css
  greenova/templates/base.html
Labels: Django, CSS

#23 Feature/makefile improvement
  .env.vault
  .gitignore
  Makefile
  gitignore
  setup.py
Labels: enhancement, Makefile

#28 Feature/chatbot - Implemented Chatbot Serialiser/Data
  Makefile
  docs/chatdata.md
  greenova/chatbot/create_input.py
  greenova/chatbot/data/chatdata-serialised.protobin
  greenova/chatbot/data/chatdata.proto
  greenova/chatbot/data/chatdata_pb2.py
  greenova/chatbot/services.py
  greenova/chatbot/templates/chatbot/chat_widget.html
  greenova/chatbot/views.py
  greenova/chatdata-serialised
  greenova/static/css/defines/colours.css
  greenova/templates/base.html
Labels: enhancement, Django

#46 Feature/consolidate-css
  .pre-commit-config.yaml
  greenova/dashboard/templates/dashboard/dashboard.html
  greenova/dashboard/templates/dashboard/partials/dashboard_content.html
  greenova/dashboard/templates/dashboard/partials/overdue_count.html
  greenova/dashboard/templates/dashboard/profile.html
  greenova/dashboard/templatetags/dashboard_tags.py
  greenova/dashboard/urls.py
  greenova/dashboard/views.py
  greenova/greenova/settings.py
  greenova/mechanisms/views.py
  greenova/obligations/templates/obligations/components/_obligations_summary.html
  greenova/obligations/templates/obligations/components/_pagination.html
  greenova/obligations/urls.py
  greenova/obligations/views.py
  greenova/procedures/templates/procedures/procedure_charts.html
  greenova/projects/models.py
  greenova/projects/templates/projects/projects_selector.html
  greenova/projects/views.py
  greenova/static/css/styles.css
  greenova/static/css/themes/dark.css
  greenova/static/css/vendor/pico-classless.min.css
  greenova/templates/base.html
  greenova/theme/static_src/package.json
  greenova/theme/static_src/src/base.css
  greenova/theme/static_src/src/components/breadcrumbs.css
  greenova/theme/static_src/src/components/button.css
  greenova/theme/static_src/src/components/card.css
  greenova/theme/static_src/src/components/charts.css
  greenova/theme/static_src/src/components/chat.css
  greenova/theme/static_src/src/components/chatbot.css
  greenova/theme/static_src/src/components/company.css
  greenova/theme/static_src/src/components/filter.css
  greenova/theme/static_src/src/components/form.css
  greenova/theme/static_src/src/components/list.css
  greenova/theme/static_src/src/components/navigation.css
  greenova/theme/static_src/src/components/obligations.css
  greenova/theme/static_src/src/components/pagination.css
  greenova/theme/static_src/src/components/user-profile.css
  greenova/theme/static_src/src/defines/colours.css
  greenova/theme/static_src/src/defines/design.css
  greenova/theme/static_src/src/styles.css
  greenova/theme/static_src/src/themes/dark.css
  greenova/theme/static_src/src/themes/light.css
  greenova/theme/static_src/src/vendor/pico-classless.min.css
  greenova/theme/templates/base.html
Labels: Django, ui

#41 Add Responsibility in CRUD Form Drop-Down List
  .env.vault
  .github/.copilot-test-instructions.md
  .github/prompts/github-issue.prompt.md
  .vscode/launch.json
  .vscode/settings.json
  ACKNOWLEDGEMENTS.md
  conftest.py
  docs/TESTING.md
  docs/templates/github-issue-template.md
  greenova/core/__init__.py
  greenova/core/apps.py
  greenova/core/signals.py
  greenova/core/utils/roles.py
  greenova/core/views.py
  greenova/dashboard/test_dashboard.py
  greenova/dashboard/views.py
  greenova/greenova/settings.py
  greenova/manage.py
  greenova/obligations/admin.py
  greenova/obligations/forms.py
  greenova/obligations/models.py
  greenova/obligations/templates/obligations/components/_obligations_summary.html
  greenova/obligations/templates/obligations/form.html
  greenova/obligations/templates/obligations/form/new_obligation.html
  greenova/obligations/templates/obligations/form/update_obligation.html
  greenova/obligations/templates/obligations/form/view_obligation.html
  greenova/obligations/templatetags/obligation_tags.py
  greenova/obligations/test_obligations.py
  greenova/obligations/utils.py
  greenova/obligations/views.py
  greenova/projects/test_projects.py
  greenova/projects/views.py
  greenova/responsibility/admin.py
  greenova/responsibility/figures.py
  greenova/responsibility/models.py
  greenova/responsibility/templatetags/responsibility_tags.py
  greenova/responsibility/test_responsibility.py
  greenova/responsibility/urls.py
  greenova/responsibility/views.py
  greenova/templates/base.html
  greenova/users/templates/users/admin_user_list.html
  greenova/users/templates/users/messages/password_reset_key_message.txt
  greenova/users/templates/users/messages/password_reset_key_subject.txt
  greenova/users/templates/users/partials/admin_user_list.html
  greenova/users/test_users.py
  greenova/users/tests.py
  greenova/users/views.py
  pyproject.toml
  pytest.ini
  requirements.txt
  setup.py
  tools/pre_commit/test_pre_commit_wrapper.py
Labels: Django, ux
